browser=chrome
elmsurl=https://preprodelms.pi1993it.dev/pragadmin/

elmsadminuser=ppadminuser1@flipick.com

elmsadminpassword=Password!23

testlmscourse=Foundations On Demand

pmicurl=https://preprodpmic.pi1993it.dev/pmic-preprod/pragmatichome
pmicadminuser=ppadminuser1@flipick.com
pmicadminpassword=Password!23

pspurl=http://52.6.7.214/pmic-preprod/psp/pragmatichome

ondemandurl=https://preprodlms.pi1993it.dev/ondemand-preprod/pragmatichome

carturl=https://preprodcart.pi1993it.dev/

pmicstudentuser=allcourseuser1@9aug.com
pmicstudentpassword=Password!23



#Create/edit ACCOUNT test cases
AccountLegalName_initial=Mediawide
Account_phone=1234567890
Account_phone_modified=9876543210

#Create/edit CONTACT test cases
contact_firstname=testcontact
contact_lastname=lname
contact_domain=@flipick.com
contact_title=QC
contact_company=Flipick
contact_address1=address 111
contact_address2=address 222
contact_city=Pune
contact_phone=1234567890
contact_zipcode=422018
contact_country=India
contact_state=Maharashtra
contact_phone_modified=100000001

#used in updateEventStatus TCS to change event status to cancelled AND used in FrontEndOrder_DiscountCode tcs
existingeventname=Flipick- Public Online event-0613
	
	
#Create ORDER test case
#testcustomer_initial=testcustomer
#testcustomer_lastname=lastname

#For REFUND_EXISTINGORDER test case
existingorderid=000041086	

# For all  test cases where we create public online event, for ex:FrontEndOrderCC_SameBuyer, FrontEndOrderCC_NewBuyer,FrontEndOrderDiscountCode, CreatePublicOnlineEvent
testpubliconlineevent_initial=Flipick- Public Online event-
testpublicinpersonevent_initial=Flipick- Public inperson event-
testonsiteonlineevent_initial=Flipick- Onsite Online event-
testonsiteinpersonevent_initial=Flipick- Onsite Inperson event-


#this will be used while creating new event, used in FrontEndOrderDiscountCode under method(setTemplate) defined in createevent_frontendorder_page
eventTemplate=Build Online

#this will be used while creating new event and selecting PM course for it, used in FrontEndOrderDiscountCode under method(addPMProducts) defined in createevent_frontendorder_page
setBUILDPMcourse=Build

# For all  test cases where we use existing event for APPLY FILTER in Event list page. NOTE:-Its commented currently 
#for ex:FrontEndOrderCC_SameBuyer, 
#FrontEndOrderCC_NewBuyer,
#FrontEndOrderDiscountCode, 
#CreatePublicOnlineEvent, 
#Refund_FrontEndOrderCC_SameBuyer
testeventselectedforordercases=2026 dec-event1



#***For all test cases where we filter order as per this customer (method=setCustomerFilter)
#Cancel_ExistingOrder
#Edit_ExistingOrder
#Refund_ExistingOrder-commented
existingcustomer=testcustomer.6654@flipick.com


#For all test cases where we create backend order(method=createNewCustomer)
#BackEndOrderIP
#BackEndOrderPL
newcustomer_firstname=flipicktestcustomer
newcustomer_lastname=lname
newcustomer_title=Development Head
newcustomer_company=Flipick
newcustomer_mainphone=1020304050
newcustomer_address1=Address 01
newcustomer_address2=Address 02
newcustomer_city=Mumbai
newcustomer_zipcode=411014
newcustomer_country=India
newcustomer_state=Maharashtra


#For all backend order creation test cases where we add single regustrant (method= generateNewRegistrantsEmail)
#BackEndOrderIP
#BackEndOrderPL
newregistrant_initial=flipickbackendregistrant.
newregistrant_domain=@flipick.com
newregistrant_firstname=fname
newregistrant_lastname=lname
newregistrant_phone=1234567890
newregistrant_jobtitle=QC
newregistrant_company=Flipick
newregistrant_address1=address1
newregistrant_address2=address2
newregistrant_city=Adak
newregistrant_country=United States
newregistrant_state=Alaska
newregistrant_zipcode=99546

#for placing backend order when we add existing registrant (method=addExistingRegistrant)
#BackEndOrderIP
#BackEndOrderPL
existingRegistrantemailid=maninder.oberoi@flipick.com


#defined in order_backendorder_page under method=searchExistingCustomerEmail
#BackEndOrderIPFeesProduct
searchdefaultcustomer=maninder.oberoi@flipick.com


#defined in order_backendorder_page under method=addFeesRegistrants
#BackEndOrderIPFeesProduct
Fees_eventname=25Jan-Online event (10173)

#stage		
Fees_coursename=Price (10174)

Fees_existing_registrant=kmaninder28@gmail.com
#stage		testing1@fee.com
#preprod	kmaninder28@gmail.com


# for all method where we search specific customer in All Orders pages (method=setCustomerFilter)
#Refund_ExistingOrder-commented
#Cancel_ExistingOrder
#Edit_ExistingOrder
searchexistingcustomer=testcustomer

#for Create/edit contact (method=setCountry)
#CreateContacts
#EditContacts
contactcountry=India

#Used in class=CreateOnsiteOnlineEvent, CreatePublicInpersonEvent, CreatePublicOnlineEvent
#passed as argument to method= setEventStartDateTime
#secondly, defined in createevent_frontendorder_page under method=setCourseStartDateTime
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
#FrontEndOrderDiscountCode
event_startdays_fromcurrent_date=30

#Used in class=CreateOnsiteOnlineEvent, CreatePublicInpersonEvent, CreatePublicOnlineEvent
#passed as argument to method=setEventEndDateTime
#secondly, defined in createevent_frontendorder_page under method=setCourseStartDateTime
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
#FrontEndOrderDiscountCode
event_days_enddate_fromevent_startdate=15


#Used in class=CreateOnsiteOnlineEvent, CreatePublicInpersonEvent, CreatePublicOnlineEvent
#passed as argument to method=setCourseStartDateTime
#secondly, defined in createevent_frontendorder_page under method=setCourseStartDateTime
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
#FrontEndOrderDiscountCode
course_startdays_fromcurrent_date=35

#Used in class=CreateOnsiteOnlineEvent, CreatePublicInpersonEvent, CreatePublicOnlineEvent
#passed as argument to method=setCourseEndDateTime
#secondly, defined in createevent_frontendorder_page under method=setCourseStartDateTime
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
#FrontEndOrderDiscountCode
course_days_enddate_fromcourse_startdate=2



#defined in createevent_frontendorder_page under method=generateReg1Email, setRegistrantONEInfo, setRegistrantTWOInfo, setRegistrantTHREEInfo, setBillingInfo
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
#FrontEndOrderDiscountCode
cartregistrant_fnamel=pmicflipickreg1
cartPSPregistrant_fnamel=pspflipickreg1
cartODregistrant_fnamel=odflipickreg1

cartregistrant_lname1=lastname1
cartregistrant_jtitle1=Production Manager
cartregistrant_company1=mw
cartregistrant_phoneoption1=Mobile
cartregistrant_mobile1=0123456789
cartregistrant_address1_1=address11
cartregistrant_address1_2=address21
cartregistrant_city1=Adak
cartregistrant_zipcode1=99546
cartregistrant_country1=United States
cartregistrant_state1=Alaska
#AND
cartregistrant_fname2=dummyreg2
cartregistrant_lname2=lastname2
cartregistrant_jtitle2=Relationship Manager
cartregistrant_company2=Mediawide2
cartregistrant_phoneoption2=Office
cartregistrant_mobile2=0123456789
cartregistrant_address2_1=address12
cartregistrant_address2_2=address22
cartregistrant_city2=Devon
cartregistrant_zipcode2=T9G
cartregistrant_country2=Canada
cartregistrant_state2=Alberta
#AND
cartregistrant_fname3=dummyreg3
cartregistrant_lname3=lastname3
cartregistrant_jtitle3=title3
cartregistrant_company3=company3
cartregistrant_phoneoption3=Home
cartregistrant_mobile3=0123456789
cartregistrant_address3_1=address13
cartregistrant_address3_2=address23
cartregistrant_city3=Nagpur
cartregistrant_zipcode3=123456
cartregistrant_country3=India
cartregistrant_state3=Maharashtra

#defined in createevent_frontendorder_page under method=generateNewBillerEmail, setNewBillingInfo, 
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
#FrontEndOrderDiscountCode
newbillerfirstname=flipickbiller
newbillerlastname=lname
newbillerphone=12341243
newbillertitle=title
newbillercompany=apple
newbilleraddress1=M.G Road
newbilleraddress2=Camp
newbillercity=Adak	
newbillerzipcode=99546
newbillercountry=United States
newbillerstate=Alaska

#defined in createevent_frontendorder_page under method=applyCouponCode
#FrontEndOrderDiscountCode
discountcouponcode=VGAQEDS3

#defined in below test cases under method=placeFrontEndOrder and passed it to createevent_frontendorder_page method=setRegistrantItemQty
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
#FrontEndOrderDiscountCode
edititemqty=1
itemqty=1

#defined in createevent_frontendorder_page under method=setCardDetails
#FrontEndOrderCC_NewBuyer
#FrontEndOrderCC_SameBuyer
cardnumber=4111 1111 1111 1111
exp_month=01 - January
exp_year=2030
cvv=111


editandincreaseitemqty=2


##############################################PMIC admin###########################
#Add Users
newuser_firstname=flipickadmin
newuser_lastname=lastname
newuser_password=Password!23
newuser_domain=@flipick.com
newuser_role=Administrators

#Edit users data
edit_user_firstname=
edit_user_lastname=
edit_user_password=
edit_user_role=

#search user
search_adminuser_name=
search_adminuser_loginname=
search_adminuser_role=

#Roles
new_rolename=testrole1

#Search role for edition:
search_role_foredition=testroleaugust

#Search role for deletion:
search_role_fordeletion=testrole11111

#Exam Dashboard-search event
search_eventname_forsetup= BETA YES public online event-1
search_eventcourse_forsetup=Market
search_eventuser_insetup_startexam=betayesuser6@mw.com
search_eventuser_insetup_activateuser=betayesuser6@mw.com

#Exam Dashboard-activate user by setting password
setPassword=Password!23

#No. of questions in a course exam, used in "submitcourseexam" method
NoOfQuestions=20

odNoOfQuestions=20

#-----------------------------------------
odcartregistrant_fnamel=odflipickreg1
odcartregistrant_lname1=lastname1
odcartregistrant_jtitle1=Production Manager
odcartregistrant_company1=Mediawide1
odcartregistrant_phoneoption1=Mobile
odcartregistrant_mobile1=0123456789
odcartregistrant_address1_1=address11
odcartregistrant_address1_2=address21
odcartregistrant_city1=Adak
odcartregistrant_zipcode1=99546
odcartregistrant_country1=United States
odcartregistrant_state1=Alaska

#-------------------------------------------edit order details-----------------
customerupdatedfname=customernewfname
customerupdatedlname=customernewlname
customerupdatedemail=cust1@17jan.com
updatedmasteraccount=User
pickupmasteraccount=User Testing

updatedorderaccount=testmw
pickuporderaccount=User Testing
#------------------------------TBD order---------------------
twochar_tbdorderaccountname=me
toSelecttbdorderaccountname=Mediawide